### ISSUE TITLE
Add doctrine ORM 3 support

### ISSUE THREAD

**Issue by VincentLanglet** [shipmonk-rnd/doctrine-hint-driven-sql-walker#27]
Hi, currently this lib doesn't support ORM 3 cf composer.json,
https://github.com/shipmonk-rnd/doctrine-hint-driven-sql-walker/blob/master/composer.json#L9

It would be nice to add the support. I didn't have time so far to see all it imply so far.

**Comment by janedbal** [comment]
@VincentLanglet Normally, I release new versions of our libs after I verify them in our main repository, but we are not using doctrine/orm 3.0 there yet. I dont really expect any issues, but it just feels wrong to release it just because CI is green.

Or did you test it on your project?

**Comment by VincentLanglet** [comment]
> Or did you test it on your project?

I did not installed orm 3.0 yet too sorry. I was planning it and looking for any blockers.
I'll tell you if I do. (and will use the dev-master branch if needed)

**Comment by janedbal** [comment]
Just FYI, we started working on orm 3.0 transition in our main codebase, so I hope it will result in stable version supporting it within few weeks.

**Comment by VincentLanglet** [comment]
> Just FYI, we started working on orm 3.0 transition in our main codebase, so I hope it will result in stable version supporting it within few weeks.

Hi, I'm glad to here it @janedbal ; how is doing your 3.0 transition ? Is there a stable version ready to be released then ?

Thanks a lot for all your work

**Comment by VincentLanglet** [comment]
> Expect all our libs tagged at most next week. We already have ORM 3 in production 🎉

Hi, just a friendly ping ; did you encounter any issue ? It was supposed to be tagged some weeks ago :)

**Comment by janedbal** [comment]
Tagged everything except dbal4 support in https://github.com/shipmonk-rnd/doctrine-two-phase-migrations
